create table if not exists public.function_event_logs (
  id bigint generated by default as identity primary key,
  service text not null,
  level text not null default 'info',
  subject text,
  event text not null,
  detail text,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_function_event_logs_service_created_at
  on public.function_event_logs (service, created_at desc);

create index if not exists idx_function_event_logs_level_created_at
  on public.function_event_logs (level, created_at desc);

create or replace function public.log_function_event(
  p_service text,
  p_level text,
  p_subject text,
  p_event text,
  p_detail text default null,
  p_meta jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.function_event_logs (
    service,
    level,
    subject,
    event,
    detail,
    meta
  )
  values (
    left(coalesce(nullif(trim(p_service), ''), 'unknown'), 80),
    left(coalesce(nullif(trim(p_level), ''), 'info'), 16),
    case when p_subject is null then null else left(trim(p_subject), 160) end,
    left(coalesce(nullif(trim(p_event), ''), 'event'), 120),
    case when p_detail is null then null else left(trim(p_detail), 2000) end,
    coalesce(p_meta, '{}'::jsonb)
  );
end;
$$;

revoke all on function public.log_function_event(text, text, text, text, text, jsonb) from public;
grant execute on function public.log_function_event(text, text, text, text, text, jsonb) to service_role;
